### ISSUE TITLE
3 subtasks' original datasets (59-61) can't be downloaded 

### ISSUE THREAD

**Issue by Zcchill** [allenai/natural-instructions-v1#7]
3 subtasks' datasets (59-61) of v-1.1 can't be downloaded, what I could get are only the oid sha256 of these datasets. I can't use "git lfs pull" to obtain the three datasets since there aren't corresponding repo and I could only find the download url in the webside "https://instructions.apps.allenai.org/#explore". Can you update the three datasets in the webside (without the git lfs option) or upload the three datasets to this repo directly?

**Comment by danyaljj** [comment]
Thanks for bringing this to our attention! Should be fixed in 30mins or so, after the website's restarted.

**Comment by Zcchill** [comment]
> Thanks for bringing this to our attention! Should be fixed in 30mins or so, after the website's restarted.

Thank you! I have got the corresponding datasets, I will close the issue.
