### ISSUE TITLE
Any chance to have an access to the training code

### ISSUE THREAD

**Issue by nooralahzadeh** [allenai/natural-instructions-v1#8]
Hi, 
Thanks for sharing the code. Is there any chance to have an access to the training code with BART?
Thanks

**Comment by TYTTYTTYT** [comment]
Hello, I have the same question, do you have any findings?

**Comment by TYTTYTTYT** [comment]
> Hi, Thanks for sharing the code. Is there any chance to have an access to the training code with BART? Thanks

Hello, I have the same question. Do you have any findings?

**Comment by danyaljj** [comment]
We do not. But you should be able to do this easily via libraries such as Huggingface.
